name: DebugBuild
on:
  push:
    branches:
      - master
env:
  # Solution file path relative to the root directory of the repository
  SOLUTION_FILE_PATH: project/Engine.sln
  # Visual Studio configuration (Debug / Release)
  CONFIGURATION: Debug
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Build
        run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
